name: lw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.3.0
  intl: ^0.20.2
  provider: ^6.1.4
  url_launcher: ^6.3.1
  xml: ^6.5.0
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0 
  firebase_auth: ^5.3.4
  sign_in_button: ^3.2.0
  flutter_gemini: ^3.0.0
  google_generative_ai: ^0.2.2
#   flutter_launcher_icons: ^0.14.3
  
# flutter_icons:
#   android: true
#   image_path: "assets/google.png"

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
